### ISSUE TITLE
can't run the file

### ISSUE THREAD

**Issue by cxz66** [ChristopheZhao/ChaGPT-API-Call#1]
Hello blogger, I have obtained the API-key of Open AI and deployed and run it according to the steps you provided, but the running results show：‘Traceback (most recent call last):
  File "F:\python\files\ChaGPT-API-Call\test.py", line 51, in <module>
    chat_test(keys,model_name,request_address,context)
  File "F:\python\files\ChaGPT-API-Call\test.py", line 27, in chat_test
    response = res.json()['choices'][0]['message']['content']
KeyError: 'choices'’
How can I fix this?

**Comment by ChristopheZhao** [comment]
Thanks for the attention to the project, does this error happen on the first call or after several dialogs are done?If the error occurs after calling several dialogs, it may be because the length of the context exceeds the maximum limit of the API. I am still fixing this problem and will update the code later.

**Comment by cxz66** [comment]
OH,I ran the project again and was able to work correctly. It's just a little slow.
And the previous problem may be caused by my proxy settings.
Thanks for your code.

**Comment by ChristopheZhao** [comment]
@cxz66 That's ok,then i close the issues now.
